FROM node:20-alpine AS builder

WORKDIR /appli

COPY src/package*.json ./
RUN npm install

COPY src/. .

RUN npm run build

FROM nginx:1.25-alpine

COPY config/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /appli/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]